INSERT INTO STOCK_PRICE(STOCK_ID,COMPANY_NAME,COMPANY_PRICE) VALUES(101,'HCL',500.00);
INSERT INTO STOCK_PRICE(STOCK_ID,COMPANY_NAME,COMPANY_PRICE) VALUES(102,'TCS',1000.00);
INSERT INTO STOCK_PRICE(STOCK_ID,COMPANY_NAME,COMPANY_PRICE) VALUES(103,'WIPRO',1500.00);
INSERT INTO STOCK_PRICE(STOCK_ID,COMPANY_NAME,COMPANY_PRICE) VALUES(104,'DELL',2000.00);
